name       : jansson
version    : '2.12'
release    : 7
source     :
    - https://github.com/akheron/jansson/archive/v2.12.tar.gz : 76260d30e9bbd0ef392798525e8cd7fe59a6450c54ca6135672e3cd6a1642941
license    : MIT
component  : system.base
summary    : Jansson is a C library for encoding, decoding and manipulating JSON data.
emul32     : yes
description: |
    Jansson is a C library for encoding, decoding and manipulating JSON data.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
