name       : jansson
version    : 2.13.1
release    : 8
source     :
    - https://github.com/akheron/jansson/archive/v2.13.1.tar.gz : f22901582138e3203959c9257cf83eba9929ac41d7be4a42557213a22ebcc7a0
license    : MIT
component  : system.base
summary    : Jansson is a C library for encoding, decoding and manipulating JSON data.
emul32     : yes
description: |
    Jansson is a C library for encoding, decoding and manipulating JSON data.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
