name       : jansson
version    : '2.10'
release    : 6
source     :
    - https://github.com/akheron/jansson/archive/v2.10.tar.gz : b0a899f90ade82e42da0ecabc8af1fa296d69691e7c0786c4994fb79d4833ebb
license    : MIT
component  : system.base
summary    : Jansson is a C library for encoding, decoding and manipulating JSON data.
emul32     : yes
description: |
    Jansson is a C library for encoding, decoding and manipulating JSON data.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
