name       : jansson
version    : 2.7
release    : 3
source     :
    - http://www.digip.org/jansson/releases/jansson-2.7.tar.gz : 7905e6590fb316c0ff943df3dc6a21cd81a59cff7a6d12514054c359d04d78d7
license    : MIT
component  : system.base
summary    : Jansson is a C library for encoding, decoding and manipulating JSON data.
description: |
    Jansson is a C library for encoding, decoding and manipulating JSON data.
setup      : |
    %patch -lN -p1 < $pkgfiles/0001-Honor-JSON_DECODE_INT_AS_REAL-at-lexical-stage.patch
    %patch -lN -p1 < $pkgfiles/security/CVE-2016-4425.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
