name       : jansson
version    : '2.10'
release    : 5
source     :
    - http://www.digip.org/jansson/releases/jansson-2.10.tar.bz2 : 241125a55f739cd713808c4e0089986b8c3da746da8b384952912ad659fa2f5a
license    : MIT
component  : system.base
summary    : Jansson is a C library for encoding, decoding and manipulating JSON data.
emul32     : yes
description: |
    Jansson is a C library for encoding, decoding and manipulating JSON data.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
